//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Resumen { get; set; }
        public string Descripcion { get; set; }
        public int Tope_gente { get; set; }
        public bool Online { get; set; }
        public bool Activo { get; set; }
        public int Id_autor { get; set; }
        public System.DateTime Fecha_desde { get; set; }
        public System.DateTime Fecha_hasta { get; set; }
        public string Ubicacion { get; set; }
        public string Imagen_portada { get; set; }
        public float Precio { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
