//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string resumen { get; set; }
        public string descripcion { get; set; }
        public int tope_gente { get; set; }
        public bool online { get; set; }
        public bool activo { get; set; }
        public int id_autor { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public System.DateTime fecha_hasta { get; set; }
        public string ubicacion { get; set; }
        public string imagen_portada { get; set; }
    }
}
