//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEventos
{
    using AppEventos.Reglas;
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public bool Activo { get; set; }
        public bool Vendedor { get; set; }
        public string Username { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
    }
}
