//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_evento
    {
        public int Id { get; set; }
        public int Id_Evento { get; set; }
        public int Id_Usuario { get; set; }
        public bool Activo { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
    }
}
